### ISSUE TITLE
Add to Sublime Package Control

### ISSUE THREAD

**Issue by Francisc** [vhanla/SublimeTextTrans#1]
Hello,

This should be added to Sublime Package Control, it's pretty cool.

**Comment by rexdf** [comment]
Do you mind that I submit it to package control?

**Comment by rexdf** [comment]
Hello, are you online?
echo
ping

**Comment by vhanla** [comment]
@rexdf I was very busy on other tasks, thanks for your help, I just updated this plugin.

**Comment by vhanla** [comment]
Finally I took the time to pull a request to update the current package called `Transparency` and hopefully they will accept it and this plugin will be available from Package Control. 

It has been long time since @rexdf didn't update his fork. I hope he doesn't mind.

**Comment by rexdf** [comment]
Yep,  I would be happy to see you to take over this plugin. 

 I don't understand the technical detail of the assembly. I tried to merge the patch into my fork, but i didn't get the point.
