### ISSUE TITLE
ReadMe is misleading as to loose package install location for Sublime Text 3

### ISSUE THREAD

**Issue by leetNightshade** [vhanla/SublimeTextTrans#10]
I realize the wget command in your ReadMe specifies ST2, but you support for both, so I thought it'd be useful to have both listed.

Here's what I basically tried:
`git clone git://github.com/vhanla/SublimeTextTrans.git "%APPDATA%\Sublime Text 3\Packages\SublimeTextTrans"`

That didn't work, should be somewhere in the data folder:
`git clone git://github.com/vhanla/SublimeTextTrans.git "%APPDATA%\Sublime Text 3\Data\SublimeTextTrans"`

See here concerning loose packages: https://www.sublimetext.com/docs/3/packages.html

**Comment by vhanla** [comment]
It might be better locating the correct path using SublimeText's menu Preferences -> Browse Packages. That is the path where it has to be cloned in.
