### ISSUE TITLE
About Transparency Step

### ISSUE THREAD

**Issue by yuntas** [vhanla/SublimeTextTrans#12]
Mr.vhanla,

I'm yuntas.

Thanks for creating nice packages!

well, I have a question.

SublimeTextTrans can be more transparent, six step.

But, I wanna more more clear Sublime text !

Can I do it ?

or

Should I do that ?

Please teach me...

**Comment by vhanla** [comment]
@yuntas I updated this plugin to allow custom user preferences, specially for custom transparency levels, hope it helps.
