### ISSUE TITLE
Ignore previous settings

### ISSUE THREAD

**Issue by AuthorProxy** [vhanla/SublimeTextTrans#15]
Try to disable opacity, but whenever I open new file, it restore opacity to previous value. The same behaviour is when I close and open Sublime Text again. So annoying... Windows 8.1. Latest dev sublime build.

**Comment by geckoseo** [comment]
Yes, same problem. It doesn't remember the state after closing Sublime.

Or, it does.. kind of... in that if you open a file, create a new one and begin typing, or open package control, then TextTrans suddenly remembers it is there and applies the default transparency.

This means that the window suddenly becomes transparent when one begins to work. Bit disconcerting.

Hope you can fix it.

**Comment by lewins** [comment]
+1
having same problem

**Comment by vhanla** [comment]
@AuthorProxy @geckoseo @lewins Sublime Text 3 has API with limitations to trigger plugin events, hopefully the workaround I did fixes that, and now it remembers the chosen transparency level, as well to allow custom user preferences.
