### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by azcvcza** [vhanla/SublimeTextTrans#19]
After I have released the package into the folder.My defender says that SetSublimeTextLayered.exe have
HEUR/QVM20.1.C3E3.Malware.Gen.
What should I do to solve this problem

**Comment by vhanla** [comment]
The source code of SetSublimeTextLayered.exe is included, you can recompile with FlatAssembler if you like. It is clearly a false positive.

**Comment by azcvcza** [comment]
Thanks for your reply,I search the solution in China and just find that it maybe caused by some anti-virus software.
I just can say these softwares are somehow too bad.
Thanks for your keen response!
Your plugin is very useful when I want to see what it is in other window behind the SublimeText without change my
viewpoint!
