### ISSUE TITLE
doesn't work on linux ?

### ISSUE THREAD

**Issue by UtsukushiiBushido** [vhanla/SublimeTextTrans#20]
Hi, 
I'm on arch linux 64 x86_64 and no way to use feature (but i can see it ..)
any solutions ? or it doesn't work on linux ?

Thanks

**Comment by Dxhs** [comment]
I'd like this too. Why is unix like systems a problem here?

**Comment by vhanla** [comment]
Sorry, I can't make it work on Linux since SublimeText has its own window manager so this is only for Windows OS.

**Comment by hendrix666** [comment]
Ok, thanks for reply !
