### ISSUE TITLE
doesn't work on Mac OSX

### ISSUE THREAD

**Issue by xhw035** [vhanla/SublimeTextTrans#23]
doesn't work on Mac OSX

**Comment by vhanla** [comment]
As it is mentioned in Readme file, it is Windows Only, because OSX and Linux has more restrictive access to window handlers.

**Comment by yecto** [comment]
Well, we know, but the question is a little bit more like, can you @vhanla please help us to implement this on osx - linux? - for me is really important to do this on mac for a project I'm working on, hopefully you have some thoughts, thanks! :)
