### ISSUE TITLE
SetSublimeLayered.exe listed as a trojan horse

### ISSUE THREAD

**Issue by lubokkanev** [vhanla/SublimeTextTrans#28]
For some reason, McAfee treats SetSublimeLayered.exe as malware. I'm at work so I'm not the administrator and I can't whitelist the file. 

A workaround I use is to edit the binary file with a text editor and add a zero at the end.

**Comment by vhanla** [comment]
It is compiled using FlatAssembler. Here is a new binary compiled with latest FlatAssembler. 
Please, see if it is also treated as malware.
[lib.zip](https://github.com/vhanla/SublimeTextTrans/files/1864878/lib.zip)

**Comment by vhanla** [comment]
I don't know why is that. Code is clear (assembler), VirusTotal lists 6 of 67 listing it as Trojan. 
Analysis: [https://www.virustotal.com/](https://www.virustotal.com/#/file/9a3e0ddfafc9ae0d71192c312476c80d668fb96380bd1d35da59d925e3433755/detection
)

This is a **false positive**. Just compile with [Flatassembler](http://flatassembler.net/download.php).

**Comment by lubokkanev** [comment]
I confirm that the file still gets deleted by McAfee.

**Comment by MDanihy** [comment]
It downloaded fine for me now. Though smartscreen complains about it but I just ignore.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vhanla** [comment]
Well, I rewrote the source code, and tested with virustotal and finally I could manage to get rid of lines that could lead to false positives and reduced to only one detection.

Tested here [VirusTotal Analysis](https://www.virustotal.com/#/file/66b72c28f54728c6df3995b0ae026aa1aeeca96911d5b484673a502ec6592f2a/detection)

![falsepositives](https://i.imgur.com/gBrZ0PX.png)

I hope that would allow not to block this plugin.

**Comment by vhanla** [comment]
Remember it is an executable of 1024 bytes (1KB). Now source code is even smaller in lines.
