### ISSUE TITLE
Trojan detected in SetSublimeLayered.exe

### ISSUE THREAD

**Issue by acasto** [vhanla/SublimeTextTrans#29]
Symantec Endpoint Protection is flagging the file SetSublimeLayered.exe under Trojan.Gen.2. It doesn't look like this package has changed much over the last few years, but that particular file looks to have been updated in the last few days but with no corresponding entry in the changelog.

**Comment by vhanla** [comment]
As mentioned in #28 this is a false positive.

Analysis here:
https://www.virustotal.com/#/file/9a3e0ddfafc9ae0d71192c312476c80d668fb96380bd1d35da59d925e3433755/detection

Some antiviruses will always  have that false positive. I recompiled it using the latest assembler compiler and there it is mentioned in the commit. 

I'd like to use python script only to set SublimeText into layered mode (to support transparency), but it crashes when it is set from SublimeText plugin context, so a third executable does that (setsublimelayered.exe) and to keep it small I use assembler in order not to attach big executable file. Maybe compiled in another programming language will not be detected as malware, who knows, each antiviruses suffer from those false positives. 

The source code is there, it can be compiled by anyone and prove.

**Comment by bluephoenix71** [comment]
What about the latest version of Sublimelayered.exe?  I tried to appeal to our security team and they see it as trojan on a binary level.  How can I let them see that it's not a trojan, what are the steps that I can provide for them to test?

**Comment by vhanla** [comment]
I mentioned before, the executable is a 32bit application written entirely in assembly language, as a result the binary will be the smallest one, as you can see, the source code is provided too, it was compiled using Flatassembler, and it is disappointing that some (few) antiviruses return false positives on many small binaries. I don't know which kind of trojan can be hidden in such an small binary,  the smallest trojan (named Alison Cadwell) found is 19968 bytes, and this executable is only 1024 bytes. However, in older operating systems prior to windows and maybe windows 95, com executables were prone to viruses of 13 byte sizes (Mini variants). 
It is always a pain in the arse to deal with false positives while writing applications with non trending compilers like assembler, delphi, freepascal. 
Anyways, the source code is there, it is very small, and the executable too, hopefully that will be enough and make it easier to debug/analyze for security companies, it is small compared to binaries generated with C++ or other compilers, so it results in less bytes to analyze.
