### ISSUE TITLE
AVG Antivir treats SublimeTextTrans as a virus

### ISSUE THREAD

**Issue by gente21** [vhanla/SublimeTextTrans#32]
Two days ago Avira started to think that SublimeTextTrans has a virus, is it safe to use?

![transparencyavg](https://user-images.githubusercontent.com/1794430/43260529-6a1f7640-909f-11e8-8efb-14cb653ed56e.JPG)

**Comment by vhanla** [comment]
I don't know if it has to do with this package. If that is the case, that can only be a false positive related to `SetSublimeLayered.exe` executable included in this package. 

That executable is very tiny (1024 bytes size), and its only purpose is to change SublimeText window into layered mode so it can be applied opacity. 

Unfortunately, sometimes some antiviruses will erroneously detect it as malware.
