### ISSUE TITLE
Transparency seems not to work in Sublime Text 3

### ISSUE THREAD

**Issue by bluephoenix71** [vhanla/SublimeTextTrans#35]
Package Control: Install Package - working
Transparency - working and installed
Transparency although is not working.  I can't seem to see the background.
![transparency not working](https://user-images.githubusercontent.com/12660484/71423971-39f0c980-2642-11ea-8a3a-3fc4b42ced3c.jpg)

**Comment by Rouvem** [comment]
It is not working for me either. I'm running Version 3.2.2, Build 3211. When I open Sublime Text 3, it has an error: 
![image](https://user-images.githubusercontent.com/14916033/75918690-d0e7b800-5e21-11ea-8a54-2c22bc790274.png)

**Comment by Rouvem** [comment]
> It is not working for me either. I'm running Version 3.2.2, Build 3211. When I open Sublime Text 3, it has an error:
> ![image](https://user-images.githubusercontent.com/14916033/75918690-d0e7b800-5e21-11ea-8a54-2c22bc790274.png)

I have actually just fixed this using instructions from a previous issue by recompiling the SetSublimeLayered.asm using the flat assembler.

**Comment by vhanla** [comment]
Is most likely your antivirus removed that file, is a false positive, is the smallest executable (1KB only), source code is included, some antivirus software interfere with that.

**Comment by bluephoenix71** [comment]
Can you post your defense, findings, conclusions, supporting evidence that the 1KB file is not a virus?  I need this in order to re-submit to our Security Standards team to further review.  Thank you for doing this in advance.
    On Saturday, 7 March 2020, 12:06:00 pm PST, vhanla <notifications@github.com> wrote:  
 
 
Is most likely your antivirus removed that file, is a false positive, is the smallest executable (1KB only), source code is included, some antivirus software interfere with that.

**Comment by vhanla** [comment]
There is nothing secure, the smallest virus was Mini which some variants were even 13bytes in size, but for D.O.S. using .com fileformat, (.com format don't have MZ executable headers, they launch directly to address 100h in code segment). 

PE Executables in Vista or above might even be 252 bytes, talking about malware/virus thinking that size is parameter to detect it is not a rule. 

So, the only way is to upload my executable to VirusTotal and even you can compile it using FlatAssembler, it will create that executable. VirusTotal will likely show some antiviruses detecting some kind of virus/trojan, etc. obviously, if you compiled by yourself, and knowing what the code does, is a false positive. That is why the code is included, and Python included in sublimetext doesn't allow to call the required WinAPI to modify its window opacity, that is why it is required to use an external executable.
