### ISSUE TITLE
SetSublimeLayered.exe is not found

### ISSUE THREAD

**Issue by VTalyh** [vhanla/SublimeTextTrans#5]
![image](https://f.cloud.github.com/assets/855782/1763426/9e1d6292-670d-11e3-9337-77ac406f8656.png)

After install and restart on ST3 (Win 7)

**Comment by Magimatt** [comment]
I am having the same issue as VTalyh. After install of the plugin and restart I receive the same error window. I have removed and reinstalled both Sublime Text 3 and the transparency plugin. still gives the same error. Using Win10x64

**Comment by Magimatt** [comment]
I recently have been getting the same error upon restart of sublime text 3. Initially this plugin did work though. I'm on Win10x64

**Comment by techpavan** [comment]
Even I have the same issue. 
Win 10 Enterprise / 64 bit / Sublime Text 3.1.1 Build 3176

**Comment by afurmanczyk** [comment]
I'm also having this issue.

**Comment by RockLeeHere** [comment]
same issue

**Comment by dangngochuy289** [comment]
Its 2022, and I'm also having this issue, I don't use McAfee, does anyone know how to fix this permanently?
